<?php

$countries = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan",
    "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei (Brunei Darussalam)", "Bulgaria", "Burkina Faso", "Burundi",
    "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic (Czechia)", "Congo (DRC)", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
    "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
    "Fiji", "Finland", "France",
    "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
    "Haiti", "Holy See", "Honduras", "Hungary",
    "Ivory Coast (Côte d Ivoire)", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy",
    "Jamaica", "Japan", "Jordan",
    "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan",
    "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
    "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", 
    "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar",
    "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway",
    "Oman",
    "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
    "Qatar",
    "Romania", "Russia", "Rwanda",
    "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Palestine", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
    "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey (Türkiye)", "Turkmenistan", "Tuvalu",
    "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan",
    "Vanuatu", "Venezuela", "Vietnam",
    "Yemen",
    "Zambia", "Zimbabwe",
];











$countriesWithCode = array(
    "AF" => "Afghanistan",
    "AL" => "Albania",
    "DZ" => "Algeria",
    "AD" => "Andorra",
    "AO" => "Angola",
    "AG" => "Antigua and Barbuda",
    "AR" => "Argentina",
    "AM" => "Armenia",
    "AU" => "Australia",
    "AT" => "Austria",
    "AZ" => "Azerbaijan",
    "BS" => "Bahamas",
    "BH" => "Bahrain",
    "BD" => "Bangladesh",
    "BB" => "Barbados",
    "BY" => "Belarus",
    "BE" => "Belgium",
    "BZ" => "Belize",
    "BJ" => "Benin",
    "BT" => "Bhutan",
    "BO" => "Bolivia",
    "BA" => "Bosnia and Herzegovina",
    "BW" => "Botswana",
    "BR" => "Brazil",
    "BN" => "Brunei (Brunei Darussalam)",
    "BG" => "Bulgaria",
    "BF" => "Burkina Faso",
    "BI" => "Burundi",
    "CV" => "Cabo Verde",
    "KH" => "Cambodia",
    "CM" => "Cameroon",
    "CA" => "Canada",
    "CF" => "Central African Republic",
    "TD" => "Chad",
    "CL" => "Chile",
    "CN" => "China",
    "CO" => "Colombia",
    "KM" => "Comoros",
    "CD" => "Congo (DRC)",
    "CG" => "Congo",
    "CR" => "Costa Rica",
    "CI" => "Ivory Coast (Côte d Ivoire)",
    "HR" => "Croatia",
    "CU" => "Cuba",
    "CY" => "Cyprus",
    "CZ" => "Czech Republic (Czechia)",
    "DK" => "Denmark",
    "DJ" => "Djibouti",
    "DM" => "Dominica",
    "DO" => "Dominican Republic",
    "EC" => "Ecuador",
    "EG" => "Egypt",
    "SV" => "El Salvador",
    "GQ" => "Equatorial Guinea",
    "ER" => "Eritrea",
    "EE" => "Estonia",
    "SZ" => "Eswatini",
    "ET" => "Ethiopia",
    "FJ" => "Fiji",
    "FI" => "Finland",
    "FR" => "France",
    "GA" => "Gabon",
    "GM" => "Gambia",
    "GE" => "Georgia",
    "DE" => "Germany",
    "GH" => "Ghana",
    "GR" => "Greece",
    "GD" => "Grenada",
    "GT" => "Guatemala",
    "GN" => "Guinea",
    "GW" => "Guinea-Bissau",
    "GY" => "Guyana",
    "HT" => "Haiti",
    "VA" => "Holy See",
    "HN" => "Honduras",
    "HU" => "Hungary",
    "IS" => "Iceland",
    "IN" => "India",
    "ID" => "Indonesia",
    "IR" => "Iran",
    "IQ" => "Iraq",
    "IE" => "Ireland",
    "IL" => "Israel",
    "IT" => "Italy",
    "JM" => "Jamaica",
    "JP" => "Japan",
    "JO" => "Jordan",
    "KZ" => "Kazakhstan",
    "KE" => "Kenya",
    "KI" => "Kiribati",
    "KP" => "North Korea",
    "KR" => "South Korea",
    "KW" => "Kuwait",
    "KG" => "Kyrgyzstan",
    "LA" => "Laos",
    "LV" => "Latvia",
    "LB" => "Lebanon",
    "LS" => "Lesotho",
    "LR" => "Liberia",
    "LY" => "Libya",
    "LI" => "Liechtenstein",
    "LT" => "Lithuania",
    "LU" => "Luxembourg",
    "MK" => "North Macedonia",
    "MG" => "Madagascar",
    "MW" => "Malawi",
    "MY" => "Malaysia",
    "MV" => "Maldives",
    "ML" => "Mali",
    "MT" => "Malta",
    "MH" => "Marshall Islands",
    "MR" => "Mauritania",
    "MU" => "Mauritius",
    "MX" => "Mexico",
    "FM" => "Micronesia",
    "MD" => "Moldova",
    "MC" => "Monaco",
    "MN" => "Mongolia",
    "ME" => "Montenegro",
    "MA" => "Morocco",
    "MZ" => "Mozambique",
    "MM" => "Myanmar",
    "NA" => "Namibia",
    "NR" => "Nauru",
    "NP" => "Nepal",
    "NL" => "Netherlands",
    "NZ" => "New Zealand",
    "NI" => "Nicaragua",
    "NE" => "Niger",
    "NG" => "Nigeria",
    "NO" => "Norway",
    "OM" => "Oman",
    "PK" => "Pakistan",
    "PW" => "Palau",
    "PS" => "Palestine",
    "PA" => "Panama",
    "PG" => "Papua New Guinea",
    "PY" => "Paraguay",
    "PE" => "Peru",
    "PH" => "Philippines",
    "PL" => "Poland",
    "PT" => "Portugal",
    "QA" => "Qatar",
    "RO" => "Romania",
    "RU" => "Russia",
    "RW" => "Rwanda",
    "KN" => "Saint Kitts and Nevis",
    "LC" => "Saint Lucia",
    "VC" => "Saint Vincent and the Grenadines",
    "WS" => "Samoa",
    "SM" => "San Marino",
    "ST" => "Sao Tome and Principe",
    "SA" => "Saudi Arabia",
    "SN" => "Senegal",
    "RS" => "Serbia",
    "SC" => "Seychelles",
    "SL" => "Sierra Leone",
    "SG" => "Singapore",
    "SK" => "Slovakia",
    "SI" => "Slovenia",
    "SB" => "Solomon Islands",
    "SO" => "Somalia",
    "ZA" => "South Africa",
    "SS" => "South Sudan",
    "ES" => "Spain",
    "LK" => "Sri Lanka",
    "SD" => "Sudan",
    "SR" => "Suriname",
    "SE" => "Sweden",
    "CH" => "Switzerland",
    "SY" => "Syria",
    "TJ" => "Tajikistan",
    "TZ" => "Tanzania",
    "TH" => "Thailand",
    "TL" => "Timor-Leste",
    "TG" => "Togo",
    "TO" => "Tonga",
    "TT" => "Trinidad and Tobago",
    "TN" => "Tunisia",
    "TR" => "Turkey (Türkiye)",
    "TM" => "Turkmenistan",
    "TV" => "Tuvalu",
    "UG" => "Uganda",
    "UA" => "Ukraine",
    "AE" => "United Arab Emirates",
    "GB" => "United Kingdom",
    "US" => "United States",
    "UY" => "Uruguay",
    "UZ" => "Uzbekistan",
    "VU" => "Vanuatu",
    "VE" => "Venezuela",
    "VN" => "Vietnam",
    "YE" => "Yemen",
    "ZM" => "Zambia",
    "ZW" => "Zimbabwe"
);












// countries and its territories with disuputed
$world = array(
    "AW" => "Aruba",
    "AF" => "Afghanistan",
    "AO" => "Angola",
    "AI" => "Anguilla",
    "AL" => "Albania",
    "AX" => "Aland",
    "AD" => "Andorra",
    "AE" => "United Arab Emirates",
    "AR" => "Argentina",
    "AM" => "Armenia",
    "AS" => "American Samoa",
    "AQ" => "Antarctica",
    "TF" => "French Southern and Antarctic Lands",
    "AG" => "Antigua and Barbuda",
    "AU" => "Australia",
    "AT" => "Austria",
    "AZ" => "Azerbaijan",
    "BI" => "Burundi",
    "BE" => "Belgium",
    "BJ" => "Benin",
    "BF" => "Burkina Faso",
    "BD" => "Bangladesh",
    "BG" => "Bulgaria",
    "BH" => "Bahrain",
    "BS" => "The Bahamas",
    "BA" => "Bosnia and Herzegovina",
    "UM" => "United States Minor Outlying Islands",
    "BL" => "Saint Barthelemy",
    "BY" => "Belarus",
    "BZ" => "Belize",
    "BM" => "Bermuda",
    "BO" => "Bolivia",
    "BR" => "Brazil",
    "BB" => "Barbados",
    "BN" => "Brunei",
    "BT" => "Bhutan",
    "BW" => "Botswana",
    "CF" => "Central African Republic",
    "CA" => "Canada",
    "CH" => "Switzerland",
    "CL" => "Chile",
    "CN" => "China",
    "CI" => "Ivory Coast",
    "CM" => "Cameroon",
    "CD" => "Democratic Republic of the Congo",
    "CG" => "Republic of Congo",
    "CK" => "Cook Islands",
    "CO" => "Colombia",
    "KM" => "Comoros",
    "CV" => "Cape Verde",
    "CR" => "Costa Rica",
    "CU" => "Cuba",
    "CW" => "Curaçao",
    "KY" => "Cayman Islands",
    "CY" => "Cyprus",
    "CZ" => "Czech Republic",
    "DE" => "Germany",
    "DJ" => "Djibouti",
    "DM" => "Dominica",
    "DK" => "Denmark",
    "DO" => "Dominican Republic",
    "DZ" => "Algeria",
    "EC" => "Ecuador",
    "EG" => "Egypt",
    "ER" => "Eritrea",
    "ES" => "Spain",
    "EE" => "Estonia",
    "ET" => "Ethiopia",
    "FI" => "Finland",
    "FJ" => "Fiji",
    "FK" => "Falkland Islands",
    "FR" => "France",
    "FO" => "Faroe Islands",
    "FM" => "Federated States of Micronesia",
    "GA" => "Gabon",
    "GB" => "United Kingdom",
    "GE" => "Georgia",
    "GG" => "Guernsey",
    "GH" => "Ghana",
    "GI" => "Gibraltar",
    "GN" => "Guinea",
    "GM" => "Gambia",
    "GW" => "Guinea Bissau",
    "GQ" => "Equatorial Guinea",
    "GR" => "Greece",
    "GD" => "Grenada",
    "GL" => "Greenland",
    "GT" => "Guatemala",
    "GU" => "Guam",
    "GY" => "Guyana",
    "HK" => "Hong Kong S.A.R.",
    "HM" => "Heard Island and McDonald Islands",
    "HN" => "Honduras",
    "HR" => "Croatia",
    "HT" => "Haiti",
    "HU" => "Hungary",
    "ID" => "Indonesia",
    "IM" => "Isle of Man",
    "IN" => "India",
    "IO" => "British Indian Ocean Territory",
    "IE" => "Ireland",
    "IR" => "Iran",
    "IQ" => "Iraq",
    "IS" => "Iceland",
    "IL" => "Israel",
    "IT" => "Italy",
    "JM" => "Jamaica",
    "JE" => "Jersey",
    "JO" => "Jordan",
    "JP" => "Japan",
    "KZ" => "Kazakhstan",
    "KE" => "Kenya",
    "KG" => "Kyrgyzstan",
    "KH" => "Cambodia",
    "KI" => "Kiribati",
    "KN" => "Saint Kitts and Nevis",
    "KR" => "South Korea",
    "KW" => "Kuwait",
    "LA" => "Laos",
    "LB" => "Lebanon",
    "LR" => "Liberia",
    "LY" => "Libya",
    "LC" => "Saint Lucia",
    "LI" => "Liechtenstein",
    "LK" => "Sri Lanka",
    "LS" => "Lesotho",
    "LT" => "Lithuania",
    "LU" => "Luxembourg",
    "LV" => "Latvia",
    "MO" => "Macao S.A.R",
    "MF" => "Saint Martin",
    "MA" => "Morocco",
    "MC" => "Monaco",
    "MD" => "Moldova",
    "MG" => "Madagascar",
    "MV" => "Maldives",
    "MX" => "Mexico",
    "MH" => "Marshall Islands",
    "MK" => "Macedonia",
    "ML" => "Mali",
    "MT" => "Malta",
    "MM" => "Myanmar",
    "ME" => "Montenegro",
    "MN" => "Mongolia",
    "MP" => "Northern Mariana Islands",
    "MZ" => "Mozambique",
    "MR" => "Mauritania",
    "MS" => "Montserrat",
    "MU" => "Mauritius",
    "MW" => "Malawi",
    "MY" => "Malaysia",
    "NA" => "Namibia",
    "NC" => "New Caledonia",
    "NE" => "Niger",
    "NF" => "Norfolk Island",
    "NG" => "Nigeria",
    "NI" => "Nicaragua",
    "NU" => "Niue",
    "NL" => "Netherlands",
    "NO" => "Norway",
    "NP" => "Nepal",
    "NR" => "Nauru",
    "NZ" => "New Zealand",
    "OM" => "Oman",
    "PK" => "Pakistan",
    "PA" => "Panama",
    "PN" => "Pitcairn Islands",
    "PE" => "Peru",
    "PH" => "Philippines",
    "PW" => "Palau",
    "PG" => "Papua New Guinea",
    "PL" => "Poland",
    "PR" => "Puerto Rico",
    "KP" => "North Korea",
    "PT" => "Portugal",
    "PY" => "Paraguay",
    "PS" => "Palestine",
    "PF" => "French Polynesia",
    "QA" => "Qatar",
    "RO" => "Romania",
    "RU" => "Russia",
    "RW" => "Rwanda",
    "EH" => "Western Sahara",
    "SA" => "Saudi Arabia",
    "SD" => "Sudan",
    "SS" => "South Sudan",
    "SN" => "Senegal",
    "SG" => "Singapore",
    "GS" => "South Georgia and South Sandwich Islands",
    "SH" => "Saint Helena",
    "SB" => "Solomon Islands",
    "SL" => "Sierra Leone",
    "SV" => "El Salvador",
    "SM" => "San Marino",
    "SO" => "Somalia",
    "PM" => "Saint Pierre and Miquelon",
    "RS" => "Republic of Serbia",
    "ST" => "Sao Tome and Principe",
    "SR" => "Suriname",
    "SK" => "Slovakia",
    "SI" => "Slovenia",
    "SE" => "Sweden",
    "SZ" => "Swaziland",
    "SX" => "Sint Maarten",
    "SC" => "Seychelles",
    "SY" => "Syria",
    "TC" => "Turks and Caicos Islands",
    "TD" => "Chad",
    "TG" => "Togo",
    "TH" => "Thailand",
    "TJ" => "Tajikistan",
    "TM" => "Turkmenistan",
    "TL" => "East Timor",
    "TO" => "Tonga",
    "TT" => "Trinidad and Tobago",
    "TN" => "Tunisia",
    "TR" => "Turkey",
    "TV" => "Tuvalu",
    "TW" => "Taiwan",
    "TZ" => "United Republic of Tanzania",
    "UG" => "Uganda",
    "UA" => "Ukraine",
    "UY" => "Uruguay",
    "US" => "United States of America",
    "UZ" => "Uzbekistan",
    "VA" => "Vatican",
    "VC" => "Saint Vincent and the Grenadines",
    "VE" => "Venezuela",
    "VG" => "British Virgin Islands",
    "VI" => "United States Virgin Islands",
    "VN" => "Vietnam",
    "VU" => "Vanuatu",
    "WF" => "Wallis and Futuna",
    "WS" => "Samoa",
    "YE" => "Yemen",
    "ZA" => "South Africa",
    "ZM" => "Zambia",
    "ZW" => "Zimbabwe",
    "iso-blank--12" => "Ashmore and Cartier Islands",
    "iso-blank--27" => "Bajo Nuevo Bank (Petrel Is.)",
    "iso-blank--44" => "Clipperton Island",
    "iso-blank--46" => "Cyprus No Mans Area",
    "iso-blank--54" => "Coral Sea Islands",
    "iso-blank--58" => "Northern Cyprus",
    "iso-blank--70" => "Dhekelia Sovereign Base Area",
    "iso-blank--105" => "Indian Ocean Territories",
    "iso-blank--117" => "Baykonur Cosmodrome",
    "iso-blank--118" => "Siachen Glacier",
    "iso-blank--126" => "Kosovo",
    "iso-blank--178" => "Spratly Islands",
    "iso-blank--195" => "Scarborough Reef",
    "iso-blank--199" => "Serranilla Bank",
    "iso-blank--207" => "Somaliland",
    "iso-blank--239" => "US Naval Base Guantanamo Bay",
    "iso-blank--249" => "Akrotiri Sovereign Base Area",
);



// echo json_encode($world);


?>